// Cloudflare Worker entry. Wraps the OpenNext-generated worker so the app is
// served as usual, and adds a `scheduled` handler that runs the app's
// scheduled jobs (noon lock, auto-confirm, weekly assessment) on the cron
// trigger declared in wrangler.jsonc.
// @ts-ignore: generated by `opennextjs-cloudflare build`, absent on a fresh checkout
import { default as handler } from "./.open-next/worker.js";

interface Env {
  CRON_SECRET?: string;
  [key: string]: unknown;
}

export default {
  fetch: handler.fetch,

  async scheduled(_controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    const request = new Request("https://cron.internal/api/cron/tick", {
      headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` },
    });
    const response: Response = await handler.fetch(request, env, ctx);
    const body = await response.text();
    if (!response.ok) {
      throw new Error(`cron tick failed: ${response.status} ${body}`);
    }
    console.log("cron tick", body);
  },
} satisfies ExportedHandler<Env>;

// @ts-ignore: generated by `opennextjs-cloudflare build`, absent on a fresh checkout
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
