import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create table storage.objects(bucket_id text,name text);create table storage.buckets(id text,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;insert into auth.users values('00000000-0000-0000-0000-000000000001','erin@example.com','{}'),('00000000-0000-0000-0000-000000000002','kazzy@example.com','{}');`);
const sql=readFileSync(new URL('../supabase/setup.sql',import.meta.url),'utf8');
await db.exec(sql);
const erin='00000000-0000-0000-0000-000000000001',kazzy='00000000-0000-0000-0000-000000000002';
const actor=async id=>db.exec(`select set_config('request.jwt.claim.sub','${id}',false)`);
await actor(erin);
await db.exec(`select challenge_sync()`);
assert.equal((await db.query(`select count(*)::int n from challenge_profiles`)).rows[0].n,2);
// Use actual Toronto date in the configured interval for a deterministic present-time edit.
await db.exec(`update challenge_config set start_date=(now() at time zone 'America/Toronto')::date,end_date=(now() at time zone 'America/Toronto')::date+2,allow_same_day=true`);
// Same-day logging is normally rejected; the app only offers days that have ended.
await assert.rejects(()=>db.exec(`update challenge_config set allow_same_day=false where id=1;select challenge_log('prayer',(now() at time zone 'America/Toronto')::date,true)`),/not available/);
await db.exec(`update challenge_config set allow_same_day=true where id=1`);
await db.exec(`select challenge_log('prayer',(now() at time zone 'America/Toronto')::date,false)`);
assert.equal((await db.query(`select count(*)::int n from challenge_points where user_id='${erin}' and rule_id='prayer' and not voided and not forgiven`)).rows[0].n>=1,true);
await db.exec(`select challenge_log('prayer',(now() at time zone 'America/Toronto')::date,true)`);
let entry=(await db.query(`select * from challenge_entries where user_id='${erin}' and rule_id='prayer' and day=(now() at time zone 'America/Toronto')::date`)).rows[0];
await assert.rejects(()=>db.exec(`select challenge_review('${entry.id}','approve')`),/partner/);
await actor(kazzy);await db.exec(`select challenge_review('${entry.id}','approve')`);
assert.equal((await db.query(`select status from challenge_entries where id='${entry.id}'`)).rows[0].status,'confirmed');
await actor(erin);await db.exec(`select challenge_log('prayer',(now() at time zone 'America/Toronto')::date,false)`);
const p=(await db.query(`select id from challenge_points where entry_id='${entry.id}'`)).rows[0];
await db.exec(`select challenge_forgive('${p.id}','A reasonable exception')`);
const req=(await db.query(`select id from challenge_requests where point_id='${p.id}'`)).rows[0];
await assert.rejects(()=>db.exec(`select challenge_decide('${req.id}',true)`),/partner/);
await actor(kazzy);await db.exec(`select challenge_decide('${req.id}',true)`);
assert.equal((await db.query(`select forgiven from challenge_points where id='${p.id}'`)).rows[0].forgiven,true);
await actor(erin);
await assert.rejects(()=>db.exec(`select challenge_log('time',(now() at time zone 'America/Toronto')::date,true)`),/screenshot/);
await assert.rejects(()=>db.exec(`select challenge_log('calories',(now() at time zone 'America/Toronto')::date,false)`),/not available/);
await actor('00000000-0000-0000-0000-000000000099');await assert.rejects(()=>db.exec(`select challenge_sync()`),/Unauthorized/);
await actor(erin);
await db.exec(`update challenge_config set start_date=(now() at time zone 'America/Toronto')::date-3,end_date=(now() at time zone 'America/Toronto')::date+2;select challenge_tick()`);
await db.exec(`select challenge_log('prayer',(now() at time zone 'America/Toronto')::date-2,true)`);
const late=(await db.query(`select * from challenge_entries where user_id='${erin}' and rule_id='prayer' and day=(now() at time zone 'America/Toronto')::date-2`)).rows[0];
assert.equal(late.done,false);assert.equal(late.proposed_done,true);
await actor(kazzy);await db.exec(`select challenge_review('${late.id}','approve')`);
assert.equal((await db.query(`select voided from challenge_points where entry_id='${late.id}'`)).rows[0].voided,true);
await actor(erin);await db.exec(`select challenge_log('gym',(now() at time zone 'America/Toronto')::date-2,true);select challenge_tick()`);
const lateGym=(await db.query(`select * from challenge_entries where user_id='${erin}' and rule_id='gym' and day=(now() at time zone 'America/Toronto')::date-2`)).rows[0];
assert.equal(lateGym.done,false);assert.equal(lateGym.proposed_done,true);
assert.equal((await db.query(`select count(*)::int n from challenge_points where rule_id='gym' and slot=0`)).rows[0].n,0);
await db.exec(`set role authenticated`);
await assert.rejects(()=>db.exec(`update challenge_entries set done=true`),/permission denied/);
await db.exec(`reset role`);
console.log('PASS: late corrections, no double gym penalties, direct writes blocked; schema, automatic assessment, edits, partner-only review, forgiveness, proof requirement, person-specific habits, outsider rejection.');
await db.close();
